import { Hono } from 'hono'
import type { Context } from 'hono'
import { marked } from 'marked'

type Env = { ASSETS: Fetcher }

type Note = { title: string; date: string; tag: string; category: string; url: string }

const app = new Hono<{ Bindings: Env }>()

// Notes index is build/notes.json, generated by scripts/build-notes.ts from
// frontmatter on public/pages/notes/*.md. Fetched once per isolate, then cached.
let notesCache: Note[] | null = null

async function getNotes(c: Context<{ Bindings: Env }>): Promise<Note[]> {
  if (notesCache) return notesCache
  try {
    const res = await c.env.ASSETS.fetch(new Request(new URL('/notes.json', c.req.url)))
    if (!res.ok) return []
    notesCache = await res.json()
  } catch (e) {
    console.warn('failed to load notes.json', e)
  }
  return notesCache ?? []
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

// Categorization and Filtering
function noteRowHtml(n: Note): string {
  return `
    <div class="note-row">
      <a class="note-title" href="/note/${n.url}">${escapeHtml(n.title)}</a>
      <div class="note-meta">
        <span class="note-tag tag-${escapeHtml(n.tag)}">${escapeHtml(n.tag)}</span>
        <span class="note-category">${escapeHtml(n.category)}</span>
        <span>${escapeHtml(n.date)}</span>
      </div>
    </div>
  `
}

function notesHtml(tag: string, category: string, notes: Note[]): string {
  let filtered = tag === 'all' ? notes : notes.filter(n => n.tag === tag)
  if (category !== 'all') filtered = filtered.filter(n => n.category === category)

  if (filtered.length === 0) {
    return `<div class="notes-empty">No notes yet — check back soon.</div>`
  }
  return filtered.map(noteRowHtml).join('')
}

// Shell Rendering
function shell(page: string, preload: string = '', mainClass: string = '') {
  const contentAttrs = page
    ? `hx-get="${page}" hx-trigger="load delay:50ms" hx-swap="innerHTML" hx-indicator="#loader"`
    : ''
  return `<!doctype html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Azlan Ali Khan</title>
    <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.8/dist/htmx.min.js"
      integrity="sha384-/TgkGk7p307TH7EXJDuUlgG3Ce1UVolAOFopFekQkkXihi5u/6OCvVKyz1W+idaz"
      crossorigin="anonymous"><\/script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/themes/prism.min.css">
    <script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/prism.min.js"><\/script>
    <script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-python.min.js"><\/script>
    <script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-bash.min.js"><\/script>
    <script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-json.min.js"><\/script>
    <script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-c.min.js"><\/script>
    <script src="/assets/client.js" defer><\/script>
    <link rel="stylesheet" href="/styles/main.css">
  </head>
  <body>
    <div class="htmx-indicator" id="loader"></div>
    <nav>
      <span class="nav-brand">SLICK USER</span>
      <ul class="nav-links">
        <li><a href="/" hx-get="/pages/about.html" hx-target="#content" hx-push-url="/" hx-indicator="#loader">About</a></li>
        <li><a href="/notes" hx-get="/pages/notes.html" hx-target="#content" hx-push-url="/notes" hx-indicator="#loader">Notes</a></li>
      </ul>
    </nav>
    <main${mainClass ? ` class="${mainClass}"` : ''}>
      <div id="content" ${contentAttrs}>
        ${preload}
      </div>
    </main>
    <footer>
      <p>&copy; ${new Date().getFullYear()} Azlan Ali Khan. All rights reserved.</p>
    </footer>
  </body>
  </html>`
}

function noteShell(title: string, content: string, slug: string, notes: Note[]): string {
  const sidebarItems = notes.map(n => `
    <a class="sidebar-note ${n.url === slug ? 'active' : ''}"
       href="/note/${n.url}"
       hx-get="/note/${n.url}"
       hx-target="#note-article"
       hx-push-url="/note/${n.url}">
      <span class="sidebar-tag tag-${n.tag}">${n.tag}</span>
      ${n.title}
    </a>
  `).join('')

  return `
    <div class="note-layout">
      <aside class="note-sidebar">
        <a class="breadcrumb"
           href="/notes"
           hx-get="/pages/notes.html"
           hx-target="#content"
           hx-push-url="/notes">← Notes</a>
        <div class="sidebar-list">${sidebarItems}</div>
      </aside>
      <div id="note-article">
        <article class="note-content" data-slug="${slug}">
          <h1>${title}</h1>
${noteMetaHtml(slug, wordCount(content), notes)}
          ${content}
        </article>
      </div>
    </div>
  `
}


function wordCount(html: string): number {
  const text = html.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim()
  return text ? text.split(' ').length : 0
}

function noteMetaHtml(slug: string, wt: number, notes: Note[]): string {
  const n = notes.find(x => x.url === slug)
  const mins = Math.max(1, Math.round(wt / 200))
  const tag = n?.tag ?? 'note'
  return `
    <div class="note-meta-header">
      <span class="note-tag tag-${escapeHtml(tag)}">${escapeHtml(tag)}</span>
      ${n ? `<span class="note-category">${escapeHtml(n.category)}</span>` : ''}
      ${n ? `<span class="note-date">${escapeHtml(n.date)}</span>` : ''}
      <span class="note-readtime">${mins} min read</span>
    </div>
  `
}

function obsidianToMd(text: string, slug: string): string {
  // convert ![[image.png]] to the appropriate image
  return text.replace(/!\[\[(.+?)\]\]/g, (_, filename) => {
    return `![${filename}](/assets/notes/${slug}/${encodeURI(filename)})`
  })
}

const CALLOTYPES: Record<string, string> = {
  note: 'note', info: 'info', tip: 'tip', success: 'success',
  warning: 'warning', danger: 'danger', error: 'danger', question: 'question',
  example: 'example', abstract: 'abstract', todo: 'todo',
}

function calloutsToHtml(text: string, slug: string): string {
  return text.replace(/^> \[!(\w+)\]([^\n]*)(?:\n(?:> .*|>))*/gm, (block, rawType, rawTitle) => {
    const kind = CALLOTYPES[String(rawType).toLowerCase()] ?? 'note'
    const lines = block.split('\n')
    const heading = String(lines.shift() ?? '').replace(/^>\s*\[!\w+\]\s*/, '').trim() || String(rawType)
    const body = lines.map(l => l.replace(/^>\s?/, '')).join('\n').trim()
    const bodyHtml = body ? marked(obsidianToMd(body, slug)) : ''
    return `<div class="callout callout-${kind}"><p class="callout-title">${escapeHtml(heading)}</p>${bodyHtml}</div>`
  })
}

// Note route — reads markdown from assets
app.get('/note/:slug', async (c) => {
  const slug = c.req.param('slug')
  const [notes, res] = await Promise.all([
    getNotes(c),
    c.env.ASSETS.fetch(new Request(new URL(`/pages/notes/${slug}.md`, c.req.url))),
  ])
  if (!res.ok) return c.html(shell('/pages/notes.html'), 404)
  const text = await res.text()
  const processed = calloutsToHtml(obsidianToMd(text, slug), slug)
  const content = await marked(processed) as string
  const meta = notes.find(n => n.url === slug)
  const title = meta?.title ?? slug.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())

  if (c.req.header('HX-Request')) {
    return c.html(`
      <article class="note-content" data-slug="${slug}">
        <h1>${title}</h1>
        ${noteMetaHtml(slug, wordCount(content), notes)}
        ${content}
      </article>
    `)
  }

  return c.html(shell('', noteShell(title, content, slug, notes), 'note-main'))
})

// Filter endpoint
app.get('/notes/filter', async (c) => {
  const tag = c.req.query('tag') || 'all'
  const category = c.req.query('category') || 'all'
  return c.html(notesHtml(tag, category, await getNotes(c)))
})

// Search endpoint — matches titles and note contents
app.get('/notes/search', async (c) => {
  const notes = await getNotes(c)
  const q = (c.req.query('q') || '').trim().toLowerCase()
  if (!q) return c.html(notesHtml('all', 'all', notes))

  const results: Note[] = []
  for (const n of notes) {
    const assetUrl = new URL(`/pages/notes/${n.url}.md`, c.req.url)
    const res = await c.env.ASSETS.fetch(new Request(assetUrl))
    if (!res.ok) continue
    const text = (await res.text()).toLowerCase()
    if (n.title.toLowerCase().includes(q) || text.includes(q)) results.push(n)
  }

  if (results.length === 0) {
    return c.html(`<div class="notes-empty">No notes match “${escapeHtml(c.req.query('q') || '')}”.</div>`)
  }
  return c.html(results.map(noteRowHtml).join(''))
})

// Notes page — static partial drawn via htmx; the list self-populates on load
app.get('/notes', (c) => c.html(shell('/pages/notes.html')))

// Shell routes
app.get('/', (c) => c.html(shell('/pages/about.html')))
app.get('/about', (c) => c.html(shell('/pages/about.html')))

// Fall through to static assets for everything else
app.get('*', (c) => c.env.ASSETS.fetch(c.req.raw))

export default app
